project_name: sport-data-solution-poc
office_address: "1362 Av. des Platanes, 34970 Lattes"
slack_channel: "#sport-avantages"
redpanda:
  topic: "sport_activities"
  brokers: "redpanda:9092"
simulation:
  months_history: 12
  min_activities_per_employee: 8
  max_activities_per_employee: 40
