name: "sport_data_dbt"
version: "1.0.0"
config-version: 2

profile: "sport_data_dbt"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sport_data_dbt:
    +materialized: view
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
    monitoring:
      +schema: monitoring
      +materialized: view
